name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "stage" label
        id: label-check
        run: |
          echo "LABEL_FOUND=false" >> $GITHUB_ENV
          for label in $(jq -r '.pull_request.labels[].name' <<< "${{ toJson(github.event) }}"); do
            if [ "$label" == "stage" ]; then
              echo "LABEL_FOUND=true" >> $GITHUB_ENV
            fi
          done

      - name: Run the job if "stage" label exists
        if: env.LABEL_FOUND == 'true'
        run: echo "Stage label found, running the job."
